/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Converted to TypeScript
*/

import React, { useRef, useEffect } from "react";
import { Group, Mesh, Material } from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

// Type for the GLTF model
type PlanetGLTF = GLTF & {
  nodes: {
    Sphere: Mesh;
    Sphere2: Mesh;
    Ring: Mesh;
  };
  materials: {
    [key: string]: Material;
  };
};


// Props type for R3F group, with optional scale
type PlanetProps = React.ComponentProps<'group'> & {
  scale?: number;
};

export function Planet({ scale = 1, ...props }: PlanetProps) {
  // References to different parts of the model
  const shapeContainer = useRef<Group>(null!);
  const spheresContainer = useRef<Group>(null!);
  const ringContainer = useRef<Mesh>(null!);

  const { nodes, materials } = useGLTF("/models/Planet.glb") as unknown as PlanetGLTF;

  // GSAP initial animation (runs once)
  useEffect(() => {
    const tl = gsap.timeline();

    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 2,
      ease: "circ.out",
    });

    tl.from(
      spheresContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "-=25%"
    );

    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );
  }, []);

  // Optional: continuous rotation for spheres and ring
  useFrame((state, delta) => {
    spheresContainer.current.rotation.y += delta * 0.1;
    ringContainer.current.rotation.z += delta * 0.05;
  });

  return (
    <group ref={shapeContainer} scale={scale} {...props} dispose={null}>
      <group ref={spheresContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.001"]}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>

      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials["Material.001"]}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

// Preload the GLTF model for faster initial render
useGLTF.preload("/models/Planet.glb");
