/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Converted to TypeScript
*/

import React, { useRef } from "react";
import { Group, Mesh, Material } from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";


// Type for the GLTF model
type PlanetGLTF = GLTF & {
  nodes: {
    Sphere: Mesh;
    Sphere2: Mesh;
    Ring: Mesh;
  };
  materials: {
    [key: string]: Material;
  };
};

// Props type for R3F group, with optional scale
type PlanetProps = React.ComponentProps<"group"> & {
  scale?: number;
};

// Draco decoder CDN for faster, effortless decoding
const DRACO_DECODER = "https://www.gstatic.com/draco/versioned/decoders/1.5.7/";

export function Planet({ scale = 1, ...props }: PlanetProps) {
  // References to different parts of the model
  const shapeContainer = useRef<Group>(null!);
  const spheresContainer = useRef<Group>(null!);
  const ringContainer = useRef<Mesh>(null!);

  const { nodes, materials } = useGLTF(
    "/models/Planet-v2.glb",
    DRACO_DECODER
  ) as unknown as PlanetGLTF;

  // GSAP initial animation (runs once)
  useGSAP(() => {
    if (!shapeContainer.current || !spheresContainer.current || !ringContainer.current) return;
    
    const tl = gsap.timeline();

    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 1.5,
      ease: "power4.out",
    });

    tl.from(
      spheresContainer.current.rotation,
      {
        y: Math.PI,
        z: -Math.PI,
        duration: 3,
        ease: "power2.inOut",
      },
      "<",
    );

    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        duration: 3,
        ease: "power2.inOut",
      },
      "<",
    );
  }, { scope: shapeContainer });

  // Optional: continuous rotation for spheres and ring
  useFrame((state, delta) => {
    if (!spheresContainer.current || !ringContainer.current) return;
    spheresContainer.current.rotation.y += delta * 0.2;
    ringContainer.current.rotation.z += delta * 0.1;
  });

  if (!nodes || !materials) return null;

  return (
    <group ref={shapeContainer} scale={scale} {...props} dispose={null}>
      <group ref={spheresContainer}>
        {nodes.Sphere && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={materials["Material.002"] || materials["Material.001"]}
            rotation={[0, 2, 2]}
          />
        )}
        {nodes.Sphere2 && (
          <mesh
            receiveShadow
            geometry={nodes.Sphere2.geometry}
            material={materials["Material.001"]}
            position={[1, 1.03, -0.724]}
            rotation={[0, 0, 0.741]}
            scale={0.2}
          />
        )}
      </group>

      {nodes.Ring && (
        <mesh
          ref={ringContainer}
          castShadow
          receiveShadow
          geometry={nodes.Ring.geometry}
          rotation={[-0.124, 0.123, -0.778]}
          scale={2}
        >
          <meshStandardMaterial 
            color="#FFD700" 
            metalness={0.95} 
            roughness={0.1}
            envMapIntensity={1}
          />
        </mesh>
      )}
    </group>
  );
}


// Preload the GLTF model with Draco support
useGLTF.preload("/models/Planet-v2.glb", DRACO_DECODER);
